name: Continuous delivery

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ on-premises ]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Prepare script to be copied
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          PORT_MAPPING: ${{ secrets.PORT_MAPPING }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          sed -i \
            -e "s|db_host_change|$DB_HOST|" \
            -e "s|db_database_change|$DB_DATABASE|" \
            -e "s|db_user_change|$DB_USER|" \
            -e "s|db_pass_change|$DB_PASS|" \
            -e "s|db_port_change|$DB_PORT|" \
            -e "s|port_mapping_change|$PORT_MAPPING|" \
            -e "s|app_dir_change|$APP_DIR|" \
            "deploy/deploy.sh" 

      - name: Copy deploy script to server
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy/deploy.sh"
          target: "/tmp"

      - name: Execute script deploy.sh
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo chmod +x /tmp/deploy/deploy.sh && sudo /tmp/deploy/deploy.sh
