name: Docker build environment

on:
  pull_request: 
    branches: [ '*' ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-build.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set .env file
        run: |
          cat <<EOF > .env
          ROOT_DIR=${{ github.workspace }}
          BUILD_CONTEXT=${{ github.workspace }}/docker
          PORT_MAPPING=8080
          EOF

      - name: Build app image
        run: |
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t cadastra-visitante-app:1.0 .

      - name: Run container
        run: docker compose up -d

      - name: Wait for all containers to be running
        run: |
          echo "Waiting for all containers to be running..."
          sleep 15

      - name: Check app container status
        run: |
          STATUS=$(docker inspect --format='{{ .State.Status }}' app_cadastra_visitante)
          echo "Status of app container: $STATUS"
          if [ "$STATUS" != "running" ]; then
            echo "Error: Container app_cadastra_visitante is not running."
            docker logs app_cadastra_visitante
            exit 1
          fi
          echo "Container app_cadastra_visitante is running."

      - name: Show app container logs
        if: always()
        run: |
          echo "Showing logs for the app container..."
          docker logs app_cadastra_visitante || true

      - name: Destroy build environment
        if: always()
        run: docker compose down -v
